name: main

on:
    workflow_dispatch:
    schedule:
        - cron: "*/60 */2  *  *  *"
    watch:
        types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
            - name: Checkout
              uses: actions/checkout@v2
        
            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                python-version: 3.8

            - name: "安装依赖包requests"
              run: pip3 install  requests
            - name: "安装依赖包APScheduler"
              run: pip3 install  APScheduler

            - name: "Run yqfk"
              run: python3 yqfk.py ${{ secrets.RINKE_YQFK }}
